### ISSUE TITLE
Sprite groups no longer seem to work in 2.0

### ISSUE THREAD

**Issue by syegulalp** [pyglet/pyglet#422]
In Pyglet 2.0dev5 (Windows 10 x64), the following code:

```py
import pyglet

batch = pyglet.graphics.Batch()
bg = pyglet.sprite.SpriteGroup(0)
fg = pyglet.sprite.SpriteGroup(1)
```

generates the following error:

```
    bg = pyglet.sprite.SpriteGroup(0)
TypeError: __init__() missing 3 required positional arguments: 'blend_src', 'blend_dest', and 'program'
```

This usage is as per the documentation so I'm not sure what's wrong.

**Comment by Ross-TheBoss** [comment]
As shown by this code, the **SpriteGroup requires the texture, blend_src, blend_dst and program** arguments. These weren't provided so it threw an error. Using the **pyglet.graphics.OrderedGroup** class, however, would work with just the order argument. Have you mixed up the two classes? 
```python
class SpriteGroup(graphics.Group):
    """Shared sprite rendering group.
    The group is automatically coalesced with other sprite groups sharing the
    same parent group, texture and blend parameters.
    """

    def __init__(self, texture, blend_src, blend_dest, program, order=0, parent=None):
        """Create a sprite group.
        The group is created internally when a :py:class:`~pyglet.sprite.Sprite`
        is created; applications usually do not need to explicitly create it.
        :Parameters:
            `texture` : `~pyglet.image.Texture`
                The (top-level) texture containing the sprite image.
            `blend_src` : int
                OpenGL blend source mode; for example,
                ``GL_SRC_ALPHA``.
            `blend_dest` : int
                OpenGL blend destination mode; for example,
                ``GL_ONE_MINUS_SRC_ALPHA``.
            `program` : `~pyglet.graphics.shader.ShaderProgram`
                A custom ShaderProgram.
            `order` : int
                Change the order to render above or below other Groups.
            `parent` : `~pyglet.graphics.Group`
                Optional parent group.
        """
        super().__init__(order, parent)
        self.texture = texture
        self.blend_src = blend_src
        self.blend_dest = blend_dest
        self.program = program
```

**Comment by syegulalp** [comment]
Oho, I believe that might be my issue. Thank you!
