### ISSUE TITLE
Circular import with latest branch

### ISSUE THREAD

**Issue by caffeinepills** [pyglet/pyglet#900]
**Describe the bug**
Please provide a clear and concise description of what the bug is. 
What is happening, and what do you expect to happen. 
Current crashing on latest master branch.

**System Information:**
Windows 10
Python 3.10

**How To Reproduce**
Just run any of the examples on Windows in the latest master branch I get the following:

```py
Traceback (most recent call last):
  File "C:\Installers\Backup\pyglet\examples\hello_world.py", line 1, in <module>
    import pyglet
  File "C:\Installers\Backup\pyglet\pyglet\__init__.py", line 9, in <module>
    from typing import TYPE_CHECKING
  File "C:\Python\Python310\lib\typing.py", line 25, in <module>
    import contextlib
  File "C:\Python\Python310\lib\contextlib.py", line 6, in <module>
    from functools import wraps
  File "C:\Python\Python310\lib\functools.py", line 22, in <module>
    from types import GenericAlias
  File "C:\Installers\Backup\pyglet\pyglet\types.py", line 2, in <module>
    import ctypes
  File "C:\Python\Python310\lib\ctypes\__init__.py", line 437, in <module>
    class LibraryLoader(object):
  File "C:\Python\Python310\lib\ctypes\__init__.py", line 454, in LibraryLoader
    __class_getitem__ = classmethod(_types.GenericAlias)
AttributeError: partially initialized module 'types' has no attribute 'GenericAlias' (most likely due to a circular import)
```

**Comment by caffeinepills** [comment]
Can confirm it was broken in https://github.com/pyglet/pyglet/commit/2e64d8f2f33f059189bc06bb51bbff2764e6585c

**Comment by benmoran56** [comment]
@caffeinepills I renamed the module to "customtypes". Can you see if that fixes it on your end?

**Comment by caffeinepills** [comment]
Fixed in master.
