### ISSUE TITLE
pyglet-1.5-maintenance crash with python 3.13 on Windows

### ISSUE THREAD

**Issue by ccanepa** [pyglet/pyglet#1238]
Scripts that work with python 3.12 now crash early on python 3.13
This is Windows specific.

This can be seen with the pyglet demos hello_world.py, astraea.py or noisy.py by example, wich gives

```
D:\dev\pyglet\examples>py -3.13 hello_world.py
Traceback (most recent call last):
  File "D:\dev\pyglet\pyglet\__init__.py", line 305, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\pyglet\examples\hello_world.py", line 3, in <module>
    window = pyglet.window.Window()
             ^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\pyglet\pyglet\__init__.py", line 311, in __getattr__
    __import__(import_name)
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\dev\pyglet\pyglet\window\__init__.py", line 1912, in <module>
    from pyglet.window.win32 import Win32Window as Window
  File "D:\dev\pyglet\pyglet\window\win32\__init__.py", line 50, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "D:\dev\pyglet\pyglet\canvas\__init__.py", line 110, in <module>
    from pyglet.canvas.win32 import Win32Display as Display
  File "D:\dev\pyglet\pyglet\canvas\win32.py", line 3, in <module>
    from pyglet.libs.win32 import _user32
  File "D:\dev\pyglet\pyglet\libs\win32\__init__.py", line 41, in <module>
    from . import com
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 240, in <module>
    class COMPointer(ctypes.c_void_p, metaclass=COMPointerMeta):
    ...<18 lines>...
                    raise TypeError("Interface {} doesn't have a pointer in this class.".format(cls.__name__))
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 214, in __new__
    _pointer_type_cache[cls] = type(COMPointer)("POINTER({})".format(cls.__name__),
                                    ^^^^^^^^^^
NameError: name 'COMPointer' is not defined. Did you mean: 'COMPointerMeta'?
```

or in astraea.py

```
D:\dev\pyglet\examples\astraea>py -3.13 astraea.py
Traceback (most recent call last):
  File "D:\dev\pyglet\examples\astraea\astraea.py", line 49, in <module>
    from pyglet.gl import *
  File "D:\dev\pyglet\pyglet\gl\__init__.py", line 219, in <module>
    from .win32 import Win32Config as Config
  File "D:\dev\pyglet\pyglet\gl\win32.py", line 36, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "D:\dev\pyglet\pyglet\canvas\__init__.py", line 110, in <module>
    from pyglet.canvas.win32 import Win32Display as Display
  File "D:\dev\pyglet\pyglet\canvas\win32.py", line 3, in <module>
    from pyglet.libs.win32 import _user32
  File "D:\dev\pyglet\pyglet\libs\win32\__init__.py", line 41, in <module>
    from . import com
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 240, in <module>
    class COMPointer(ctypes.c_void_p, metaclass=COMPointerMeta):
    ...<18 lines>...
                    raise TypeError("Interface {} doesn't have a pointer in this class.".format(cls.__name__))
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 214, in __new__
    _pointer_type_cache[cls] = type(COMPointer)("POINTER({})".format(cls.__name__),
                                    ^^^^^^^^^^
NameError: name 'COMPointer' is not defined. Did you mean: 'COMPointerMeta'?
```

Windows  11   23H2, 10.0.22631

The demos work normal with python 3.12 in the same machine

**Comment by ccanepa** [comment]
pyglet version at 
```
D:\dev\pyglet\examples>git log
commit 7387e594bee7e84664f931c2d9486636e4c28f8c (HEAD -> pyglet-1.5-maintenance, tag: v1.5.29, origin/pyglet-1.5-maintenance)

Date:   Tue May 14 08:56:24 2024 +0900

    ready v1.5.29 release
```

**Comment by benmoran56** [comment]
@Square789 Sorry to bother you, but if you have time could you have a look at this?

**Comment by Square789** [comment]
This is the bug i was referring to with [the first undirected paragraph of this reply](https://github.com/pyglet/pyglet/issues/1196#issuecomment-2323194337).

I assume it would be possible to just backport all of the COM changes that happened since then, but i understand that the maintenance branch should probably change as little as possible.

I will try and figure out a fix with a small changeset

**Comment by Square789** [comment]
That took way too long, apologies. But #1243 should be able to fix it.

**Comment by benmoran56** [comment]
Thank you very much @Square789! This tests OK on my Windows 10 machine with the latest 3.13 build from Python.org.
I'll get a point release out soon. 

@ccanepa Please give it a try on your end to confirm.

**Comment by ccanepa** [comment]
tests with 3.13, 3.12, 3.11, 3.10, 3.9
Scripts run normal, except sometimes one or more tracebacks are seen when quiting.
Not exactly repeteable, by example repeatdly running astraea:

```
D:\dev\pyglet\examples\astraea>py -3.11 astraea.py
Exception ignored in: <function XA2SourceVoice.__del__ at 0x0000023292824860>
Traceback (most recent call last):
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 404, in __del__
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 414, in destroy
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -1781712576] Windows Error 0x95cd3940
Exception ignored in: <function XA2SourceVoice.__del__ at 0x0000023292824860>
Traceback (most recent call last):
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 404, in __del__
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 414, in destroy
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -1781808032] Windows Error 0x95cbc460
Exception ignored in: <function XA2SourceVoice.__del__ at 0x0000023292824860>
Traceback (most recent call last):
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 404, in __del__
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 414, in destroy
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -1781809056] Windows Error 0x95cbc060

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py

D:\dev\pyglet\examples\astraea>py -3.11 astraea.py
Exception ignored in: <function XA2SourceVoice.__del__ at 0x00000189CB724860>
Traceback (most recent call last):
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 404, in __del__
  File "D:\dev\pyglet\pyglet\media\drivers\xaudio2\interface.py", line 414, in destroy
  File "D:\dev\pyglet\pyglet\libs\win32\com.py", line 150, in _call
  File "_ctypes/callproc.c", line 1000, in GetResult
OSError: [WinError -880033696] Windows Error 0xcb8bc060

```
Notice that the tracebacks only shown when quiting, and the ones with tracebacks repeat one or more times the same traceback,

Seen tracebacks with 3.12 , 3.11, 3.10, 3.9

I guess if the tracebacks can only manifest while quiting then it's enought good fix.

@Square789 , @benmoran56 thanks for still support 1.5

**Comment by Square789** [comment]
Does the issue also appear on 3.11 without the PR applied?
I believe this might be #669, but - just like caffeinepills - i am unable to replicate it.

**Comment by ccanepa** [comment]
>Does the issue also appear on 3.11 without the PR applied?

Yes, for all of 3.12 to 3.9

Windows 11 23H2, 10.0.22631

pyglet at
```
D:\dev\pyglet\examples\astraea>git log
commit 7387e594bee7e84664f931c2d9486636e4c28f8c (HEAD, tag: v1.5.29)
Date:   Tue May 14 08:56:24 2024 +0900

    ready v1.5.29 release
```

**Comment by ccanepa** [comment]
and also with python 3.13.0

**Comment by Square789** [comment]
This PR is not the issue then, but it's interesting that you also happen to run into the `__del__`-related shutdown problems for XAudio2.
I think the best option for that is applying the [hack Benjamin suggested](https://github.com/pyglet/pyglet/issues/669#issuecomment-1306887375). I'm not sure there will be any larger changes/backports to 1.5 from 2.x, where `__del__` is not used anymore in the backend-specific audio players.

**Comment by benmoran56** [comment]
We could add that hack into the main 1.5 codebase. It's harmless enough, and will suppress the messages. 

@ccanepa there have been a lot of improvements/cleanups/etc. to the platform specific code over the years, in order to keep up with OS changes. It's not really practical to backport large changes to 1.5 anymore, so unfortunately it may cease to work on modern OSes unless someone steps up to manually merge the fixes.  These old released will remain available, because 

**Question**:  is your reliance on 1.5 due to API changes, or due to hardware support? 

**If because of API changes**:
Perhaps we can help to migrate?

**If due to hardware support:** 
It's still a long ways away, but for pyglet 3.0 we are trying to fully abstract the platform code from the rendering backend. This is mainly to add a Vulkan backend, but actually will allow us to add back a legacy GL backend as well. In fact, we have successfully tested a GL 2.0 backend (I was able to run it on an old Raspberry Pi).  The API however, will be based on the modern changes.

**Comment by ccanepa** [comment]
>We could add that hack into the main 1.5 codebase. It's harmless enough, and will suppress the messages.

Seems to work, at least for 3.13 , 3.12 ,  3.11, 3.10 
tested by:

1. checkout 1.5.30
2. aply
```
D:\dev\pyglet\examples\astraea>git diff
diff --git a/pyglet/media/drivers/xaudio2/interface.py b/pyglet/media/drivers/xaudio2/interface.py
index daf0923e..b02fd522 100644
--- a/pyglet/media/drivers/xaudio2/interface.py
+++ b/pyglet/media/drivers/xaudio2/interface.py
@@ -412,7 +412,7 @@ class XA2SourceVoice:
                 self._voice.Stop(0, 0)
                 self._voice.FlushSourceBuffers()
                 self._voice.DestroyVoice()
-            except TypeError:
+            except (TypeError, OSError):
                 pass

             self._voice = None
```

3. run astraea 20 times in each python , no tracebacks seen

>@ccanepa there have been a lot of improvements/cleanups/etc. to the platform specific code over the years, in order to keep up with OS changes. It's not really practical to backport large changes to 1.5 anymore, so unfortunately it may cease to work on modern OSes unless someone steps up to manually merge the fixes.

Understandable

>Question: is your reliance on 1.5 due to API changes, or due to hardware support?

API changes, but not really. just missing the motivation to put xx hours of work. 

>If because of API changes:
Perhaps we can help to migrate?

Thats a very kind offer, but still no motivation.

**Comment by benmoran56** [comment]
I just pushed out a 1.5.31 release, that includes that small fix. I'll close this now. Thanks again @Square789 for taking time on this!

@ccanepa if you ever get the motivation to update, pop into the Discord server and i'm sure you'll be able to get any assistance you need.
