### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Batch'

### ISSUE THREAD

**Issue by nilswagner** [pyglet/pyglet#94]
The attached script leads to the above error message. I am using pyglet version 2.0.dev0 and trimesh version 3.3.6

[test_trimesh.py.txt](https://github.com/pyglet/pyglet/files/3813815/test_trimesh.py.txt)

**Comment by benmoran56** [comment]
It looks like `trimesh` will need a small change to work with pyglet 2.0. Namely, it is explicitly disabling the `shadow_window`, which should no longer be done unless a Window/context will be explicitly created. That will be a simple change. 

However, even with that change in `trimesh`, pyglet 2.0 needs a little more work on the default shaders before it's ready for use.

**Comment by nilswagner** [comment]
The current situation using 
>>> trimesh.__version__
'3.7.0'

git/pyglet/pyglet/graphics/__init__.py", line 499, in _get_domain
    domain = domain_map[key]
KeyError: (('v3f/static', 'n3f/static', 'c4B/static'), 4, True, 3)

and finally
git/pyglet/pyglet/graphics/vertexattribute.py", line 291, in __init__
    assert self.location != -1, "'{0}' attribute not found in Shader".format(self.name)
AssertionError: 'normals' attribute not found in Shader

**Comment by benmoran56** [comment]
Closing this for now, since pyglet 2.0 is not yet finalized. Trimesh will need some small changes made to work, but it might not make sense to tackle those now until the API is set for pyglet 2.0. 

Lets follow up on this once pyglet 2.0 betas are ready.
