### ISSUE TITLE
[2.0] Shader doesn't compile

### ISSUE THREAD

**Issue by r58Playz** [pyglet/pyglet#263]
Shaders don't compile using Pyglet 2.0.

Possible solution: use a context manager

**Comment by benmoran56** [comment]
Could you provide a little more information?

**Comment by r58Playz** [comment]
Shader doesn't compile due to NameError.

Full traceback:
```py
Exception ignored in: <function Shader.__del__ at 0x7fb116885790>
Traceback (most recent call last):
  File "/home/toshit/pyglet-help/pyglet-master/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self.id)
  File "/home/toshit/pyglet-help/pyglet-master/pyglet/graphics/shader.py", line 183, in id
    return self.__class__._id
AttributeError: type object 'Shader' has no attribute '_id'
Exception ignored in: <function Shader.__del__ at 0x7fb116885790>
Traceback (most recent call last):
  File "/home/toshit/pyglet-help/pyglet-master/pyglet/graphics/shader.py", line 198, in __del__
    glDeleteShader(self.id)
  File "/home/toshit/pyglet-help/pyglet-master/pyglet/graphics/shader.py", line 183, in id
    return self.__class__._id
AttributeError: type object 'Shader' has no attribute '_id'
```

**Comment by benmoran56** [comment]
Can you post your two shaders?

**Comment by r58Playz** [comment]
I used the default shaders.
