### ISSUE TITLE
AttributeError: 'Batch' object has no attribute 'add'

### ISSUE THREAD

**Issue by albertz** [pyglet/pyglet#696]
I assume I do sth wrong, but I don't really know what. This is from an old project of mine, and it used arcade and pyglet, and now I was just trying it out, and I got `AttributeError: 'Batch' object has no attribute 'add'` while trying to call `batch.add`, where `batch` is a class of instance `Batch`.

I have pyglet 2.0.dev23 installed.

When looking at the code of `Batch`, I also don't see any such method `add`. Although the documentation says there should be such a method.

When searching for this error, I did not find anything.

**Comment by caffeinepills** [comment]
`Batch.add` is only for pyglet 1.5. This has been removed in 2.0. Most likely the code you are using was developed under 1.5, I would install the latest version of that.

**Comment by albertz** [comment]
So it means the documentation is not up-to-date?
https://pyglet.readthedocs.io/en/latest/modules/graphics/index.html#pyglet.graphics.Batch.add

It says "latest".

How do I need to change the code to make it work for pyglet 2?

**Comment by csd4ni3l** [comment]
you need batch=batch in all the classes that use it

**Comment by csd4ni3l** [comment]
so the batch parameter

**Comment by albertz** [comment]
In which class? In the `Batch` class?
Currently my code is:
```python
batch.add(4, pyglet.gl.GL_QUADS, None,
            ('v2i', [x1, y1, x2, y1, x2, y2, x1, y2]),
            ('c4B', [200, 200, 220, 255] * 4)
        )
```

**Comment by csd4ni3l** [comment]
oh you are using gl, then i cant help sorry, i dont know opengl

**Comment by albertz** [comment]
I just found the migration guide (https://pyglet.readthedocs.io/en/master/programming_guide/migration.html).
But it doesn't really help me. I have no idea based on that what I now need to change...

**Comment by caffeinepills** [comment]
2.0.dev23 is a developmental release, it is not yet the latest.

You need to uninstall the current version and install 1.5.27

**Comment by albertz** [comment]
PyPI normally should only install the latest stable. I just did `pip install`, nothing else. So this is an error then that I get the dev release at not the latest stable?

**Comment by csd4ni3l** [comment]
linux or windows?

**Comment by albertz** [comment]
> PyPI normally should only install the latest stable. I just did `pip install`, nothing else. So this is an error then that I get the dev release at not the latest stable?

Sorry, to be more exact, I did `pip3 install arcade`, and arcade installed pyglet as a dependency.
Now I just see this:
```
arcade 2.6.16 requires pyglet==2.0.dev23, but you have pyglet 1.5.27 which is incompatible.
```

**Comment by albertz** [comment]
> linux or windows?

Mac.

**Comment by csd4ni3l** [comment]
oh newest arcade needs newest pyglet, or its not gonna work, so you can only migrate

**Comment by csd4ni3l** [comment]
ok i just googled it and its pyglet.graphics.draw, and i think because its draw, you need it in on_draw

**Comment by caffeinepills** [comment]
Arcade uses 2.0 which uses Modern GL and is what they have required as their base version.

Other projects that are older that use just Pyglet will need to use 1.5 .

**Comment by csd4ni3l** [comment]
link: https://pyglet.readthedocs.io/en/latest/programming_guide/graphics.html

**Comment by albertz** [comment]
Hm Arcade 2.2 seems to be fine with pyglet 1.5, but I get a very strange seemingly unrelated error:
```
Traceback (most recent call last):
  File "/Users/az/Programmierung/PyOverheadGame/./main.py", line 5, in <module>
    import arcade
  File "/Users/az/.local/lib/python3.9/site-packages/arcade/__init__.py", line 72, in <module>
    from arcade import tilemap
  File "/Users/az/.local/lib/python3.9/site-packages/arcade/tilemap.py", line 32, in <module>
    def read_tmx(tmx_file: str) -> pytiled_parser.objects.TileMap:
AttributeError: module 'pytiled_parser' has no attribute 'objects'
```

Maybe it's not worth it to try to find a combination of version packages which works with the old code, and instead rewrite the code for latest Arcade stable which requires pyglet 2.

But then, it would be nice if the migration guide could be extended a bit on the graphics part. I haven't touched the code in years and have not used pyglet or arcade ever since, and have no idea based on the current migration guide what to do.

It looks like I have some sort of vertex list:
```python
class Rectangle(object):
    """
    Draws a rectangle into a batch.
    """
    def __init__(self, x1, y1, x2, y2, batch):
        import pyglet
        self.vertex_list = batch.add(4, pyglet.gl.GL_QUADS, None,
            ('v2i', [x1, y1, x2, y1, x2, y2, x1, y2]),
            ('c4B', [200, 200, 220, 255] * 4)
        )
```

How do I convert this code?

**Comment by csd4ni3l** [comment]
downgrade or upgrade pytiled_parser, idk which one, and for the rectangle make a draw function in which you have pyglet.graphics.draw with the parameters of batch.add and call that function in on_draw

**Comment by albertz** [comment]
> for the rectangle make a draw function in which you have pyglet.graphics.draw with the parameters of batch.add and call that function in on_draw

Ok this seems to work but then I also get another arcade 2.6 error. I guess it needs some more migration work.

So I downgraded to Arcade 2.3, just for testing. Then I still got this error:
`AttributeError: module 'pytiled_parser' has no attribute 'objects'`

> downgrade or upgrade pytiled_parser, idk which one

pytiled_parser==0.9 seems to resolve this error.

But now I again get some other error. This seems arcade 2.3 related though, so I won't spam it here.

But I maybe should also update the code to directly work with Arcade 2.6...

**Comment by einarf** [comment]
Strongly consider upgrading to arcade 2.6 at the very least and use pyglet 2.0. Then you will be working with code that is activly supported and maintained. There's nothing wrong with mixing pyglet and arcade rendering. Arcade 2.7 will resolve the last issues related to mixed usage.

**Comment by benmoran56** [comment]
Since 2.0 is going to be released very soon, I just switched the "latest" documentation to point towards the master branch.
It's recommended to use 2.0 for all new projects. The documentation (particularly the `graphics` section) should explain more.

**Comment by benmoran56** [comment]
Closing, since pyglet 2.0 has been released, and all the documentation should line up.
